# Generated by Django 4.2.15 on 2025-08-30 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', '用户消息'), ('assistant', '助手回复'), ('system', '系统消息')], max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('trust_score', models.FloatField(blank=True, null=True, verbose_name='信任分数')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间戳')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'chat_message',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QueryContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_entities', models.JSONField(default=dict, verbose_name='提取的实体')),
                ('intent', models.CharField(blank=True, max_length=100, verbose_name='意图')),
                ('data_sources', models.JSONField(default=list, verbose_name='数据源')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessage', verbose_name='消息')),
            ],
            options={
                'verbose_name': '查询上下文',
                'verbose_name_plural': '查询上下文',
                'db_table': 'query_context',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'db_table': 'chat_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='会话'),
        ),
    ]
